package localgitmirror.idea.actions

import com.intellij.notification.NotificationGroupManager
import com.intellij.notification.NotificationType
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.fileChooser.FileChooser
import com.intellij.openapi.fileChooser.FileChooserDescriptor
import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.openapi.progress.ProgressManager
import com.intellij.openapi.progress.Task
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.LocalFileSystem
import localgitmirror.idea.git.GitLocal
import localgitmirror.idea.settings.SecretsStore
import localgitmirror.idea.workkit.WorkKit
import java.io.File

class ApplyLocalDumpAction : AnAction() {
  override fun actionPerformed(e: AnActionEvent) {
    val project: Project = e.project ?: return
    val baseDir = project.basePath
    if (baseDir.isNullOrBlank()) {
      notify(project, "Cannot determine project directory", NotificationType.ERROR)
      return
    }
    val projectDir = File(baseDir)

    if (SecretsStore.syncPassword.isBlank()) {
      notify(project, "Configure Sync Password in settings", NotificationType.WARNING)
      return
    }
    if (!GitLocal.isCleanWorkTree(project, projectDir)) {
      notify(project, "Working tree has uncommitted changes. Commit/stash before applying.", NotificationType.WARNING)
      return
    }

    val descriptor = FileChooserDescriptor(true, false, false, false, false, false)
    descriptor.title = "Select encrypted sync package (.bin)"
    descriptor.description = "Pick cache_*.bin generated by LocalGitMirror"
    descriptor.withFileFilter { vf -> vf.extension?.equals("bin", ignoreCase = true) == true || vf.extension?.equals("dmp", ignoreCase = true) == true }

    val baseVf = LocalFileSystem.getInstance().findFileByIoFile(projectDir)
    val chosen = FileChooser.chooseFile(descriptor, project, baseVf) ?: return
    val dumpFile = File(chosen.path)
    if (!dumpFile.exists() || !dumpFile.isFile) {
      notify(project, "Selected file does not exist", NotificationType.ERROR)
      return
    }

    val mode = Messages.showEditableChooseDialog(
      "Apply mode",
      "LocalGitMirror: Apply local sync package",
      null,
      arrayOf("new-branch", "ff-only"),
      "new-branch",
      null
    )?.trim()?.lowercase().orEmpty()
    if (mode.isBlank()) return

    val branchName: String? = if (mode == "new-branch") {
      val defaultName = "local-import-${System.currentTimeMillis()}"
      Messages.showInputDialog(project, "New branch name", "LocalGitMirror: Apply sync package", null, defaultName, null)?.trim()
    } else null
    if (mode == "new-branch" && branchName.isNullOrBlank()) return

    ProgressManager.getInstance().run(object : Task.Backgroundable(project, "LocalGitMirror: Apply sync package", false) {
      override fun run(indicator: ProgressIndicator) {
        indicator.text = "Preparing local apply"
        indicator.text = "Applying sync package"
        val res = WorkKit.runStealthApply(
          workDir = projectDir,
          password = SecretsStore.syncPassword,
          dumpFile = dumpFile,
          mode = mode,
          newBranchName = branchName
        )
        if (!res.ok()) {
          notify(project, "Apply failed: ${res.stderr.take(500)}", NotificationType.ERROR)
          return
        }
        notify(project, "Sync package applied successfully", NotificationType.INFORMATION)
      }
    })
  }

  private fun notify(project: Project, message: String, type: NotificationType) {
    NotificationGroupManager.getInstance()
      .getNotificationGroup("LocalGitMirror")
      .createNotification(message, type)
      .notify(project)
  }
}
